version: "2.4"
services:
    deepjavalibrary_container:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8888:8888
        volumes:
            - ./:/home/jupyter
        restart: always

