name: Canary-ARM64-MacOS

on:
  workflow_call:
    inputs:
      repo-id:
        description: 'staging repository id to test'
        required: false
        type: string
        default: ''
      djl-version:
        description: 'djl version to test'
        type: string
        required: false
      pt-version:
        description: 'pytorch version to test'
        type: string
        required: false
        default: ''
  workflow_dispatch:
    inputs:
      repo-id:
        description: 'staging repository id to test'
        required: false
        default: ''
      djl-version:
        description: 'djl version to test'
        required: false
      pt-version:
        description: 'pytorch version to test'
        required: false
        default: ''

jobs:
  canary-test-arm64-osx:
    if: github.repository == 'deepjavalibrary/djl-demo'
    runs-on: [ self-hosted, ARM64, macOS ]
    env:
      AWS_REGION: us-east-1
      DJL_STAGING: ${{github.event.inputs.repo-id}}
      DJL_VERSION: ${{github.event.inputs.djl-version}}
      PT_VERSION: ${{github.event.inputs.pt-version}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11
          architecture: aarch64
      - name: Test PyTorch
        working-directory: canary
        run: |
          set -x
          DJL_ENGINE=pytorch-native-auto PYTORCH_VERSION=$PT_VERSION ./gradlew clean run
          rm -rf $HOME/.djl.ai/
          DJL_ENGINE=pytorch-native-auto PYTORCH_VERSION=1.13.1 ./gradlew clean run
          rm -rf $HOME/.djl.ai/
          DJL_ENGINE=pytorch-native-auto PYTORCH_VERSION=2.0.1 ./gradlew clean run
          rm -rf $HOME/.djl.ai/
          DJL_ENGINE=pytorch-native-auto PYTORCH_VERSION=2.1.1 ./gradlew clean run
          rm -rf $HOME/.djl.ai/
          DJL_ENGINE=pytorch-native-cpu ./gradlew clean run
          rm -rf $HOME/.djl.ai/
          DJL_ENGINE=pytorch-native-cpu PT_VERSION=1.13.1 ./gradlew clean run
          rm -rf $HOME/.djl.ai/
          DJL_ENGINE=pytorch-native-cpu PT_VERSION=2.0.1 ./gradlew clean run
          rm -rf $HOME/.djl.ai/
          DJL_ENGINE=pytorch-native-cpu PT_VERSION=2.1.1 ./gradlew clean run
          rm -rf $HOME/.djl.ai/
      - name: Test OnnxRuntime
        working-directory: canary
        run: |
          set -x
          DJL_ENGINE=onnxruntime ./gradlew clean run
          rm -rf $HOME/.djl.ai/
      - name: Test Huggingface tokenizers
        working-directory: canary
        run: |
          set -x
          DJL_ENGINE=tokenizers ./gradlew clean run
          rm -rf $HOME/.djl.ai/
      - name: Test SentencePiece tokenizers
        working-directory: canary
        run: |
          set -x
          DJL_ENGINE=sentencepiece ./gradlew clean run
          rm -rf /root/.djl.ai/
      # MXNet doesn't support aarch64
      # TensorFlow doesn't support aarch64
      # PaddlePaddle doesn't support aarch64
      # fastText doesn't support aarch64
      # TFLite doesn't support aarch64
      # Xgboost doesn't support aarch64 ?
      # LightGBM doesn't support aarch64 ?
